# This file was generated by GoReleaser. DO NOT EDIT.
class Gitpert < Formula
  desc "measure the pertinence of git authors as a time-decayed measure of LOC added and removed to a repository (or a set of files in a repository)"
  homepage "https://github.com/augmentable-dev/gitpert/"
  version "0.0.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/augmentable-dev/gitpert/releases/download/v0.0.6/gitpert_0.0.6_Darwin_x86_64.tar.gz"
    sha256 "8defd5e142f62506fb90b77f4d16d1ead2fba5ba81c3316de93d9a569df9ecf1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/augmentable-dev/gitpert/releases/download/v0.0.6/gitpert_0.0.6_Linux_x86_64.tar.gz"
      sha256 "184e320fd1da31aa7963fa624000a12d99d142069fe2b956e50a30ceac70c420"
    end
  end

  def install
    bin.install "gitpert"
  end
end
